
spring:
  #rabbitmq:
    #host: localhost
    #port: 15672
    #username: guest
    #password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: jfm
    driverClassName: com.mysql.cj.jdbc.Driver
